-
    directory: ''
    file: index.html
    saveAs: index.html
    menuItem: Home
    menuNode: .
    enabled: true
    new: true
-
    directory: about
    file: index.html
    saveAs: about.html
    menuItem: About
    menuNode: .
    enabled: true
    new: true
-
    directory: agility
    file: index.html
    saveAs: agility.html
    menuItem: Agility
    menuNode: .
    enabled: true
    new: true
-
    directory: contact
    file: index.html
    saveAs: contact.html
    menuItem: Contact
    menuNode: .
    enabled: true
    new: true
-
    directory: faq
    file: index.html
    saveAs: faq.html
    menuItem: Faq
    menuNode: .
    enabled: true
    new: true
-
    directory: gallery/daisy
    file: index.html
    saveAs: gallery/daisy.html
    menuItem: Daisy
    menuNode: gallery
    enabled: true
    new: true
-
    directory: gallery/douglas
    file: index.html
    saveAs: gallery/douglas.html
    menuItem: Douglas
    menuNode: gallery
    enabled: true
    new: true
-
    directory: gallery/poppy
    file: index.html
    saveAs: gallery/poppy.html
    menuItem: Poppy
    menuNode: gallery
    enabled: true
    new: true
-
    directory: gallery/puppies
    file: index.html
    saveAs: gallery/puppies.html
    menuItem: Puppies
    menuNode: gallery
    enabled: true
    new: true
-
    directory: gallery/ziggy
    file: index.html
    saveAs: gallery/ziggy.html
    menuItem: Ziggy
    menuNode: gallery
    enabled: true
    new: true
-
    directory: gallery
    file: null
    saveAs: gallery/index.html
    menuItem: Gallery
    menuNode: .
    enabled: true
    new: true
-
    directory: grooming
    file: index.html
    saveAs: grooming.html
    menuItem: Grooming
    menuNode: .
    enabled: true
    new: true
-
    directory: history
    file: index.html
    saveAs: history.html
    menuItem: History
    menuNode: .
    enabled: true
    new: true
-
    directory: links
    file: index.html
    saveAs: links.html
    menuItem: Links
    menuNode: .
    enabled: true
    new: true
-
    directory: origin
    file: index.html
    saveAs: origin.html
    menuItem: Origin
    menuNode: .
    enabled: true
    new: true
-
    directory: puppy-care
    file: index.html
    saveAs: puppy-care.html
    menuItem: Puppy-care
    menuNode: .
    enabled: true
    new: true
-
    directory: standard
    file: index.html
    saveAs: standard.html
    menuItem: Standard
    menuNode: .
    enabled: true
    new: true
-
    directory: stuff
    file: index.html
    saveAs: stuff.html
    menuItem: Stuff
    menuNode: .
    enabled: false
    new: true
-
    directory: testimonial
    file: index.html
    saveAs: testimonial.html
    menuItem: Testimonial
    menuNode: .
    enabled: true
    new: true
